#!/bin/bash

if [[ $1 == "" ]];  then
    echo "usage: ./checkOutput.sh RELEASE1"
    exit
fi

export rel=$1


for sample in zee zmm ttbar qcd
do

  echo ""
  echo $sample "sample" 
  export done=`grep System ${rel}/${sample}.log`
  if [[ ! $done == "" ]];  then
      echo "DONE"
  else
      export nevent=`grep processing ${rel}/${sample}.log | tail -n 1 | awk '{print $4}'`
      echo $nevent "event"
  fi

done



echo ""
