#!/bin/bash


if [[ $1 == "" ]] || [[ $2 == "" ]];  then
    echo "usage: ./tcmetValidation RELEASE1 RELEASE2"
    exit
fi

export rel1=$1
export rel2=$2

./tcmetValidation zee   $rel1 $rel2 MC
./tcmetValidation zmm   $rel1 $rel2 MC
./tcmetValidation ttbar $rel1 $rel2 MC
./tcmetValidation qcd   $rel1 $rel2 MC
#./tcmetValidation data  $rel1 $rel2 DATA

export webdir=${rel1}_${rel2}
echo "Copying to dir" $webdir

if [ ! -d /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir ] 
    then
    mkdir /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir
else
    rm -r /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir
    mkdir /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir
fi

scp -r $rel2/webpage/*html  /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir/.
scp -r $rel2/webpage/plots/ /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir/.
fs sa /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir webserver:afs read
fs sa /afs/cern.ch/user/b/benhoob/www/tcmetValidation/$webdir/plots webserver:afs read
