#!/usr/bin/bash

#------------------------------------------------------
#USAGE: python makeConfigFiles.py dataset globaltag key
#------------------------------------------------------

#CMSSW_3_6_1 datasets
python makeConfigFiles.py  /RelValZEE/CMSSW_3_6_1-START36_V7-v1/GEN-SIM-RECO             START36_V7::All  zee
python makeConfigFiles.py  /RelValZMM/CMSSW_3_6_1-START36_V7-v1/GEN-SIM-RECO             START36_V7::All  zmm
python makeConfigFiles.py  /RelValTTbar/CMSSW_3_6_1-START36_V7-v1/GEN-SIM-RECO           START36_V7::All  ttbar
python makeConfigFiles.py  /RelValQCD_Pt_80_120/CMSSW_3_6_1-START36_V7-v1/GEN-SIM-RECO   START36_V7::All  qcd


#run jobs
cmsRun  zee.py   > zee.log   &
cmsRun  zmm.py   > zmm.log   &
cmsRun  ttbar.py > ttbar.log &
cmsRun  qcd.py   > qcd.log   &
