#!/bin/bash

if [[ $1 == "" ]];  then
    echo "usage: ./validateRelease RELEASE"
    exit
fi

#source stuff
#. /afs/cern.ch/cms/sw/cmsset_default.sh
#. /afs/cern.ch/cms/LCG/LCG-2/UI/cms_ui_env.sh
. /afs/cern.ch/cms/LCG/LCG-2/UI/cms_ui_env.sh

#call cmsenv in official release directory
echo ""
echo "-------------------------------------------------------------------------------------"
echo  "Validating release             :  " $1
export reldir=`scram list -c | grep " $1 " | awk '{print $3}'`
echo  "Release directory              :  " $reldir
cd $reldir/src
eval `scramv1 runtime -sh`
cd -

#make release directory, copy files there
if [ ! -d $1 ]; then
    mkdir $1
    mkdir $1/webpage
    mkdir $1/webpage/plots
fi

cp getDataset.py      $1/.
cp getGlobalTag.py    $1/.
cp makeConfigFiles.py $1/.
cp template.py        $1/.
cp data.py            $1/.
cd $1

export release=$1
#export release=CMSSW_3_8_1

#if [ 0 = 1 ]; then

#zee sample
echo "-------------------------------------------------------------------------------------"

export zeedataset=`python getDataset.py ZEE ${release} | tail -n 1`
echo  "ZEE dataset                    :  " $zeedataset
echo   $zeedataset > .zeedataset

export zeeglobaltag=`dbsql find dataset.tag where dataset like ${zeedataset} | tail -n 1`
echo  "ZEE globaltag                  :  " $zeeglobaltag

python makeConfigFiles.py $zeedataset $zeeglobaltag zee tcMet

cmsRun zee.py > zee.log 2>&1 &


#zmm sample
echo "-------------------------------------------------------------------------------------"

export zmmdataset=`python getDataset.py ZMM ${release} | tail -n 1`
echo  "ZMM dataset                    :  " $zmmdataset
echo  $zmmdataset > .zmmdataset

export zmmglobaltag=`dbsql find dataset.tag where dataset like ${zmmdataset} | tail -n 1`
echo  "ZMM globaltag                  :  " $zmmglobaltag

python makeConfigFiles.py $zmmdataset $zmmglobaltag zmm tcMet

cmsRun zmm.py > zmm.log 2>&1 &

#ttbar sample
echo "-------------------------------------------------------------------------------------"

export ttbardataset=`python getDataset.py TTbar ${release} | tail -n 1`
echo  "TTBAR dataset                  :  " $ttbardataset
echo  $ttbardataset > .ttbardataset

export ttbarglobaltag=`dbsql find dataset.tag where dataset like ${ttbardataset} | tail -n 1`
echo  "TTBAR globaltag                :  " $ttbarglobaltag

python makeConfigFiles.py $ttbardataset $ttbarglobaltag ttbar tcMet

cmsRun ttbar.py > ttbar.log 2>&1 &

#fi

#qcd sample
echo "-------------------------------------------------------------------------------------"

export qcddataset=`python getDataset.py QCD_Pt_80_120 ${release} | tail -n 1`
echo  "QCD dataset                    :  " $qcddataset
echo  $qcddataset > .qcddataset

export qcdglobaltag=`dbsql find dataset.tag where dataset like ${qcddataset} | tail -n 1`
echo  "QCD globaltag                  :  " $qcdglobaltag

python makeConfigFiles.py $qcddataset $qcdglobaltag qcd tcMet

cmsRun qcd.py > qcd.log 2>&1 &

#data sample
echo "-------------------------------------------------------------------------------------"

#cmsRun data.py > data.log 2>&1 &
#echo  '/MinimumBias/Commissioning10-GOODCOLL-Jun9thSkim_v1/RECO'  > .datadataset


rm -f validateRelease.log
echo "-----------------------------------------------------------------------------------------------"  >> validateRelease.log
echo  "Validating release             :  " $1                                                           >> validateRelease.log
echo  "Release directory              :  " $reldir                                                      >> validateRelease.log
echo "-----------------------------------------------------------------------------------------------"  >> validateRelease.log
echo  "ZEE dataset                    :  " $zeedataset                                                  >> validateRelease.log
echo  "ZEE globaltag                  :  " $zeeglobaltag                                                >> validateRelease.log
echo "-----------------------------------------------------------------------------------------------"  >> validateRelease.log
echo  "ZMM dataset                    :  " $zmmdataset                                                  >> validateRelease.log
echo  "ZMM globaltag                  :  " $zmmglobaltag                                                >> validateRelease.log
echo "-----------------------------------------------------------------------------------------------"  >> validateRelease.log
echo  "TTBAR dataset                  :  " $ttbardataset                                                >> validateRelease.log
echo  "TTBAR globaltag                :  " $ttbarglobaltag                                              >> validateRelease.log
echo "-----------------------------------------------------------------------------------------------"  >> validateRelease.log
echo  "QCD dataset                    :  " $qcddataset                                                  >> validateRelease.log
echo  "QCD globaltag                  :  " $qcdglobaltag                                                >> validateRelease.log
echo "-----------------------------------------------------------------------------------------------"  >> validateRelease.log


