#!/bin/csh -f

#setenv rootdir 'root\/'
setenv rootdir ''
setenv nevents -1

#PEAK
cat cfg/collisions_template_cfg.py | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'peak.root/g' | sed 's/inputfile/Alignment.PeakDecoResiduals.DataSetMinBias_38Tpeak_cff/g' | sed 's/bookTH1bool/True/g' | sed 's/bookTH2bool/False/g'  >! cfg/collisions_peak_cfg.py

#DECO
cat cfg/collisions_template_cfg.py | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'deco.root/g' | sed 's/inputfile/Alignment.PeakDecoResiduals.DataSetMinBias_38Tdec_cff/g' | sed 's/bookTH1bool/True/g' | sed 's/bookTH2bool/False/g'  >! cfg/collisions_deco_cfg.py

#PEAKTH2
cat cfg/collisions_template_cfg.py | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'peak_TH2.root/g' | sed 's/inputfile/Alignment.PeakDecoResiduals.DataSetMinBias_38Tpeak_cff/g' | sed 's/bookTH1bool/False/g' | sed 's/bookTH2bool/True/g'  >! cfg/collisions_peak_TH2_cfg.py

#DECOTH2
cat cfg/collisions_template_cfg.py | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'deco_TH2.root/g' | sed 's/inputfile/Alignment.PeakDecoResiduals.DataSetMinBias_38Tdec_cff/g' | sed 's/bookTH1bool/False/g' | sed 's/bookTH2bool/True/g'  >! cfg/collisions_deco_TH2_cfg.py

