#!/bin/csh -f

#setenv rootdir 'root\/'
setenv rootdir ''

#PEAK
cat cfg/crab_collisions_template.cfg | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'peak.root/g' | sed 's/cfgfile/collisions_peak_cfg.py/g' | sed 's/crabruns/123596/g' | sed 's/trial/'$1'/g' | sed 's/workdir/peak/g' >! cfg/crab_collisions_peak.cfg

#DECO
cat cfg/crab_collisions_template.cfg | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'deco.root/g' | sed 's/cfgfile/collisions_deco_cfg.py/g' | sed 's/crabruns/124275/g' | sed 's/trial/'$1'/g' | sed 's/workdir/deco/g' >! cfg/crab_collisions_deco.cfg

#PEAKTH2
cat cfg/crab_collisions_template.cfg | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'peak_TH2.root/g' | sed 's/cfgfile/collisions_peak_TH2_cfg.py/g' | sed 's/crabruns/123596/g' | sed 's/trial/'$1'/g' | sed 's/workdir/peak_TH2/g' >! cfg/crab_collisions_peak_TH2.cfg

#DECOTH2
cat cfg/crab_collisions_template.cfg | sed 's/nevents/'${nevents}'/g' | sed 's/rootfilename/'${rootdir}'deco_TH2.root/g' | sed 's/cfgfile/collisions_deco_TH2_cfg.py/g' | sed 's/crabruns/124275/g' | sed 's/trial/'$1'/g' | sed 's/workdir/deco_TH2/g' >! cfg/crab_collisions_deco_TH2.cfg

