#!/bin/csh -f

if($1 == '') then
    setenv peakdir    `cat dirs.txt | awk '{print $1}'`
    setenv decodir    `cat dirs.txt | awk '{print $2}'`
    setenv basedir    `cat dirs.txt | awk '{print $3}'`
    setenv dir        `cat dirs.txt | awk '{print $4}'`
else 
    setenv peakdir    `cat $basedir/trial$1/dirs.txt | awk '{print $1}'`
    setenv decodir    `cat $basedir/trial$1/dirs.txt | awk '{print $2}'`
    setenv basedir    `cat $basedir/trial$1/dirs.txt | awk '{print $3}'`    
    setenv dir        `cat $basedir/trial$1/dirs.txt | awk '{print $4}'`
endif
