#!/bin/csh -f

if($1 == '') then
    source getdirs
else
    source getdirs $1
endif

echo "Getting peakdir"
crab -status    -c $peakdir
crab -getoutput -c $peakdir

echo "Getting decodir"
crab -status    -c $decodir
crab -getoutput -c $decodir



