#!/bin/csh -f

if($1 == '') then
    source getdirs
else
    source getdirs $1
endif

echo "Removing peakdir files: " $peakdir
rm $peakdir/res/*.root

echo "Removing decodir files: " $decodir
rm $decodir/res/*.root 

