#!/bin/csh -f

if($1 == '') then
    setenv nevents 1000
else 
    setenv nevents $1
endif

source copycfg
echo "Submitting" $nevents "events"

mkdir /tmp/benhoob/root/
mkdir /tmp/benhoob/log/
ln -s /tmp/benhoob/root
ln -s /tmp/benhoob/log

cmsRun cfg/collisions_peak_cfg.py      >& /tmp/benhoob/log/peak.log     &
cmsRun cfg/collisions_deco_cfg.py      >& /tmp/benhoob/log/deco.log     &
cmsRun cfg/collisions_peak_TH2_cfg.py  >& /tmp/benhoob/log/peak_TH2.log &
cmsRun cfg/collisions_deco_TH2_cfg.py  >& /tmp/benhoob/log/deco_TH2.log &




