#!/bin/csh -f

setenv basedir   crabjobs
setenv dir trial`ls -l ${basedir}/ | wc | awk '{print $1}'`
echo "Submitting to directory" $basedir/$dir 

mkdir $basedir/$dir/

echo $dir "2009 peak/deco data. 3.8T alignment. Add ntuple" > $basedir/$dir/NOTES

mkdir $basedir/$dir/root/
mkdir $basedir/$dir/plots/
mkdir $basedir/$dir/log/
mkdir $basedir/$dir/src/
mkdir $basedir/$dir/cfg/

cp cfg/PeakDecoResiduals_collisions_crab_peak.cfg  $basedir/$dir/cfg/.
cp cfg/PeakDecoResiduals_collisions_crab_deco.cfg  $basedir/$dir/cfg/.
cp cfg/PeakDecoResiduals_collisions_cfg.py         $basedir/$dir/cfg/.
cp ../plugins/PeakDecoResiduals.cc                 $basedir/$dir/src/.
cp ../src/TrackerValidationVariables.cc            $basedir/$dir/src/.
cp ../interface/TrackerValidationVariables.h       $basedir/$dir/src/.

echo "Creating peak job"
crab -create -cfg cfg/PeakDecoResiduals_collisions_crab_peak.cfg
setenv peakdir `ls -ltrd crab_* | tail -1 | awk '{print $9}' | sed 's/\///g'`
echo "Copying peakdir"
cp -r $peakdir/ $basedir/$dir/.
rm -r $peakdir/
ln -s $basedir/$dir/$peakdir
echo "Submitting peak job" $peakdir
echo "PEAK" > $peakdir/NOTES
crab -submit all -c

echo "Creating deco job"
crab -create -cfg cfg/PeakDecoResiduals_collisions_crab_deco.cfg
setenv decodir `ls -ltrd crab_* | tail -1 | awk '{print $9}' | sed 's/\///g'`
echo "Copying decodir"
cp -r $decodir/ $basedir/$dir/.
rm -r $decodir/
ln -s $basedir/$dir/$decodir
echo "Submitting deco job" $decodir
echo "DECO" > $decodir/NOTES
crab -submit all -c

echo $peakdir $decodir $basedir $dir >! dirs.txt
cp dirs.txt $basedir/$dir/.
