#!/bin/csh -f

setenv basedir /nfs-3/userdata/benhoob/crabjobs
setenv dir trial`ls -l ${basedir}/ | wc | awk '{print $1}'`
echo "Submitting to directory" $basedir/$dir 

mkdir $basedir/$dir/

echo $dir "/MinimumBias/Commissioning10-GOODCOLL-v8/RAW-RECO CMSSW_3_5_6 INCLUDE ntuple Feb 2010 cosmics alignment 500 jobs" > $basedir/$dir/NOTES
#echo $dir "/MinimumBias/Commissioning10-Apr1Skim_GOODCOLL-v1/RAW-RECO CMSSW_3_5_6 INCLUDE ntuple Feb 2010 cosmics alignment" > $basedir/$dir/NOTES

mkdir $basedir/$dir/root/
mkdir $basedir/$dir/plots/
mkdir $basedir/$dir/log/
mkdir $basedir/$dir/src/
mkdir $basedir/$dir/cfg/

cp cfg/PeakDecoResiduals_collisions_crab_peak.cfg  $basedir/$dir/cfg/.
cp cfg/PeakDecoResiduals_collisions_crab_deco.cfg  $basedir/$dir/cfg/.
cp cfg/PeakDecoResiduals_collisions_cfg.py         $basedir/$dir/cfg/.
cp ../plugins/PeakDecoResiduals.cc                 $basedir/$dir/src/.
cp ../src/TrackerValidationVariables.cc            $basedir/$dir/src/.
cp ../interface/TrackerValidationVariables.h       $basedir/$dir/src/.

#echo "Creating peak job"
#crab -create -cfg cfg/PeakDecoResiduals_collisions_crab_peak.cfg
#setenv peakdir `ls -ltrd crab_* | tail -1 | awk '{print $9}' | sed 's/\///g'`
#echo "Copying peakdir"
#cp -r $peakdir/ $basedir/$dir/.
#rm -r $peakdir/
#ln -s $basedir/$dir/$peakdir
#echo "Submitting peak job" $peakdir
#echo "PEAK" > $peakdir/NOTES
#crab -submit all -c

echo "Creating deco job"
crab -create -cfg cfg/PeakDecoResiduals_collisions_crab_deco.cfg
setenv decodir `ls -ltrd crab_* | tail -1 | awk '{print $9}' | sed 's/\///g'`
echo "Copying decodir"
cp -r $decodir/ $basedir/$dir/.
rm -r $decodir/
ln -s $basedir/$dir/$decodir
echo "Submitting deco job" $decodir
echo "DECO" > $decodir/NOTES
crab -submit all -c

setenv peakdir NOPEAKDIR
echo $peakdir $decodir $basedir $dir >! dirs.txt
cp dirs.txt $basedir/$dir/.
