#!/bin/csh -f

setenv trialnum trial2
mkdir ${trialnum}
nsmkdir $mycastor/PeakDecoResiduals/${trialnum}
rfchmod 755 $mycastor/PeakDecoResiduals/${trialnum}

source copycrab ${trialnum}

echo "Creating peak job"
crab -create -cfg cfg/crab_collisions_peak.cfg
crab -submit all -c ${trialnum}/peak

echo "Creating deco job"
crab -create -cfg cfg/crab_collisions_deco.cfg
crab -submit all -c ${trialnum}/deco

echo "Creating peakTH2 job"
crab -create -cfg cfg/crab_collisions_peak_TH2.cfg
crab -submit all -c ${trialnum}/peak_TH2

echo "Creating decoTH2 job"
crab -create -cfg cfg/crab_collisions_deco_TH2.cfg
crab -submit all -c ${trialnum}/deco_TH2





#setenv peakdir `ls -ltrd crab_* | tail -1 | awk '{print $9}' | sed 's/\///g'`
#echo "Copying peakdir" $peakdir
#cp -r $peakdir/ /tmp/benhoob/.
#rm -r $peakdir/
#ln -s /tmp/benhoob/$peakdir
