#!/bin/csh -f

if($1 == '') then
    source getdirs
else
    source getdirs $1
endif

echo "Getting peakdir"
crab -status    -c $peakdir
echo "Getting decodir"
crab -status    -c $decodir
echo "Getting peakdirTH2"
crab -status    -c $peakdirTH2
echo "Getting decodirTH2"
crab -status    -c $decodirTH2


