#!/bin/csh -f

if($1 == '') then
    source getdirs
else
    source getdirs $1
endif

echo "Removing peakdir files: " $peakdir
rm $peakdir/res/*.root

echo "Removing decodir files: " $decodir
rm $decodir/res/*.root 

echo "Removing peakdirTH2 files: " $peakdirTH2
rm $peakdirTH2/res/*.root 

echo "Removing decodirTH2 files: " $decodirTH2
rm $decodirTH2/res/*.root 


